development:
  secret_key_base: ef3474241677eb80ccad77e71ae48b3315671c55b2a55307df4ea62dbec6150450017fabf106eb7902695c04225dde1f6691c5400d49f4d228f2dd208981328c
  google_api_key: AIzaSyAvnqaAFuiAlXMuFIaPGWkRgmnxSmLII3o
  host: localhost
  url: http://localhost:5000
  pusher_app_id: '425841'
  pusher_app_key: '2fd9acbd37b06708983b'
  pusher_app_secret: '7a3dba4ceaab5040da47'
  moi_app_url: http://localhost:8100/#

test:
  secret_key_base: ef3474241677eb80ccad77e71ae48b33
  google_api_key: nokey
  host: localhost
  url: http://localhost:5000

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  host: moi-staging.herokuapp.com
  url: https://moi-staging.herokuapp.com
  pusher_app_id: <%= ENV["PUSHER_APP_ID"] %>
  pusher_app_key: <%= ENV["PUSHER_APP_KEY"] %>
  pusher_app_secret: <%= ENV["PUSHER_APP_SECRET"] %>
  moi_app_url: http://moi-frontend.herokuapp.com/#
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUD_API_KEY"] %>
  api_secret: <%= ENV["CLOUD_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false

integration:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  host: moi-integration.herokuapp.com
  url: https://moi-integration.herokuapp.com
  pusher_app_id: <%= ENV["PUSHER_APP_ID"] %>
  pusher_app_key: <%= ENV["PUSHER_APP_KEY"] %>
  pusher_app_secret: <%= ENV["PUSHER_APP_SECRET"] %>
  moi_app_url: http://moi-frontend.herokuapp.com/#

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  delayed_job_user: <%= ENV["DELAYED_JOB_USER"] %>
  delayed_job_password: <%= ENV["DELAYED_JOB_PASSWORD"] %>
  host: moi-backend.growmoi.com
  url: http://moi-backend.growmoi.com
  pusher_app_id: <%= ENV["PUSHER_APP_ID"] %>
  pusher_app_key: <%= ENV["PUSHER_APP_KEY"] %>
  pusher_app_secret: <%= ENV["PUSHER_APP_SECRET"] %>
  moi_app_url: http://moi.growmoi.com/#
